TOASTAINER_API_HOST                         ?= api.toastate.link
VERSION                                     ?= 0.1
REVISION                                    ?= 1
ARCHI                                       ?= amd64